url: https://xinjiangshao.com
enforce_ssl: xinjiangshao.com
name: Xinjiang's Stuff
description: "Web Developer, App Developer, and Much More"
meta_description: "Xinjiang is a developer works in Chicago"
highlighter: rouge
logo: false
paginate: 15
domain_name: 'http://xinjiangshao.com'
google_analytics: 'UA-66561519-1'
author:         
  twitter:
    username: soleoshao
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
